spring.application.name=demo

spring.jpa.hibernate.ddl-auto=update 
spring.datasource.url=jdbc:mysql://localhost:3306/Libraries
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.username=root
spring.datasource.password=Ahmed@22
spring.jpa.show.sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

logging.level.org.hibernate=info
logging.level.org.hibernate.SQL=debug
spring.jpa.properities.hibernate.jdbc.time_zone=UTC


// jackson no fail serialize  when convert java object to json  
#spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false


#Logging properties

#disable log in console
#logging.pattern.console=
#
#logging.logback.rollingpolicy.max-file-size=5MB
#logging.logback.rollingpolicy.max-history=5
#
#logging.file.name=G:/Logging/global/logs/global.log
#logging.level.root=INFO


//custom properties

scheduler.enabled=false   // nor run schedule becaues be default is true
price-interval=PT02S
interval.in.cron=0 * * * * *


//flyway_core
#
#spring.flyway.enabled=true
#spring.flyway.baseline-on-migrate=true
#spring.flyway.locations=classpath:Migration
#spring.flyway.validate-on-migrate=true


//Actuator

management.endpoints.web.exposure.include=*
//for-organize-the-shape
spring.jackson.serialization.indent-output=true 



//Files
file.upload.base-path=G:/BookFiles/Book/Books
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB



//Swagger

# Define the base path for the generated OpenAPI docs
springdoc.api-docs.path=/v3/api-docs

# Set the URL path for accessing Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html


#logging.level.org.springframework=DEBUG
logging.level.org.springdoc=DEBUG



//Aspect
#
#logging.level.com.example.demo.Aspect=DEBUG
#logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

#timezone

spring.jpa.properties.hibernate.jdbc.time_zone=UTC
logging.level.org.springframework.web=DEBUG
logging.level.com.example=INFO



//cache

spring.redis.host=localhost
spring.redis.port=6379
spring.cache.type=redis
